###User Index
GET http://localhost:3000/users.json

###User Show
GET http://localhost:3000/users/1.json

###User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Third"
}

###User Update
PATCH http://localhost:3000/users/2.json
Content-Type: application/json

{
  "name": "Numba 2"
}

###User Delete
DELETE http://localhost:3000/users/3.json

